version: '3.1'

services:
  treehole:
    build: ../backend/
    image: treehole_backend
    container_name: treehole_backend
    restart: always
    volumes:
      - ./docker-tomcat/webapps/ROOT/statics/imgs:/go/treehole/backend/imgs
    ports: 
      - "8088:8080"
    depends_on: 
      - mysql
      - tomcat
    networks:
      - mynet
    tty: true
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "010420"
    volumes: 
      - ./docker-db/mysql:/var/lib/mysql
      - ./docker-db/init:/docker-entrypoint-initdb.d/
    ports: 
      - "3306:3306"
    networks:
      - mynet
  tomcat:
    container_name: tomcat
    image: tomcat
    restart: always
    volumes:
      - ./docker-tomcat/conf:/usr/local/tomcat/conf
      - ./docker-tomcat/logs:/usr/local/tomcat/logs
      - ./docker-tomcat/webapps:/usr/local/tomcat/webapps
    ports:
      - "8081:8080"
    networks:
      - mynet
networks:
  mynet:
      driver: bridge
